version: 0.0
os: linux

hooks:

  BeforeInstall:
    - location: scripts/prereqs.sh
      timeout: 300
      runas: root
    - location: scripts/create_iam_role.sh
      timeout: 300
      runas: root
    - location: scripts/prereqs.sh
      timeout: 300
      runas: root 

  BeforeInstall:
    - location: scripts/prereqs.sh
      timeout: 300
      runas: root
    
       
  ApplicationStart:
    - location: scripts/deploy-service.sh
      timeout: 300
      runas: root
