version: 0.2

phases:

  prebuild:
    commands:
      - mvn clean install
      - echo Loggin into Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION  --no-linclude-email)
      - REPOSITORY_URI=649787745281.dkr.ecr.us-east-1.amazonaws.com/argocdimage
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODE_BUILD_ID | awk -F":" '{print $2}')
      
  build:
    commands:
      - echo Build completed on `date`
      - echo building the docker image
      - docker build -t  $REPOSITORY_URI:latest .
      - docker tag $REPOSITPRY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  postbuild:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
     - imagedefinitions.json
     - target/**/*.war
  discard-paths: yes
